[tool.commitizen]
name = "cz_conventional_commits"
version = "0.3.1"
tag_format = "v$version"
version_files = [
    "client/package.json:version",
    "server/package.json:version"
]
update_changelog_on_bump = true
major_version_zero = true
